// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID           string
	SimpleID     string
	Status       string
	RepoPath     string
	WorktreePath sql.NullString
	AgentModel   sql.NullString
	AgentPrompt  sql.NullString
	Error        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
