// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID           string
	SimpleID     string
	Status       SessionStatus
	BackendID    string
	RepoPath     string
	RemoteUrl    sql.NullString
	WorktreePath string
	AgentConfig  sql.NullString
	Error        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type SessionProjection struct {
	StreamID       string
	SimpleID       string
	BackendID      string
	RepoPath       string
	WorktreePath   string
	RemoteUrl      string
	AgentConfig    string
	LifecycleState string
	PublicState    string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
