// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID           string
	SimpleID     string
	Status       SessionStatus
	BackendID    string
	RepoPath     string
	WorktreePath string
	AgentConfig  sql.NullString
	Error        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
