// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id,
  simple_id,
  status,
  repo_path,
  worktree_path,
  agent_model,
  agent_prompt,
  error
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, simple_id, status, repo_path, worktree_path, agent_model, agent_prompt, error, created_at, updated_at
`

type CreateSessionParams struct {
	ID           string
	SimpleID     string
	Status       SessionStatus
	RepoPath     string
	WorktreePath sql.NullString
	AgentModel   sql.NullString
	AgentPrompt  sql.NullString
	Error        sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.SimpleID,
		arg.Status,
		arg.RepoPath,
		arg.WorktreePath,
		arg.AgentModel,
		arg.AgentPrompt,
		arg.Error,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SimpleID,
		&i.Status,
		&i.RepoPath,
		&i.WorktreePath,
		&i.AgentModel,
		&i.AgentPrompt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByID, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, simple_id, status, repo_path, worktree_path, agent_model, agent_prompt, error, created_at, updated_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SimpleID,
		&i.Status,
		&i.RepoPath,
		&i.WorktreePath,
		&i.AgentModel,
		&i.AgentPrompt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionBySimpleID = `-- name: GetSessionBySimpleID :one
SELECT id, simple_id, status, repo_path, worktree_path, agent_model, agent_prompt, error, created_at, updated_at
FROM sessions
WHERE simple_id = ?
  AND status IN ('queued', 'running', 'completed')
`

func (q *Queries) GetSessionBySimpleID(ctx context.Context, simpleID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionBySimpleID, simpleID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SimpleID,
		&i.Status,
		&i.RepoPath,
		&i.WorktreePath,
		&i.AgentModel,
		&i.AgentPrompt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, simple_id, status, repo_path, worktree_path, agent_model, agent_prompt, error, created_at, updated_at
FROM sessions
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SimpleID,
			&i.Status,
			&i.RepoPath,
			&i.WorktreePath,
			&i.AgentModel,
			&i.AgentPrompt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByStatus = `-- name: ListSessionsByStatus :many
SELECT id, simple_id, status, repo_path, worktree_path, agent_model, agent_prompt, error, created_at, updated_at
FROM sessions
WHERE status = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByStatus(ctx context.Context, status SessionStatus) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SimpleID,
			&i.Status,
			&i.RepoPath,
			&i.WorktreePath,
			&i.AgentModel,
			&i.AgentPrompt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionStatusByID = `-- name: UpdateSessionStatusByID :one
UPDATE sessions
SET status = ?,
    error = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, simple_id, status, repo_path, worktree_path, agent_model, agent_prompt, error, created_at, updated_at
`

type UpdateSessionStatusByIDParams struct {
	Status SessionStatus
	Error  sql.NullString
	ID     string
}

func (q *Queries) UpdateSessionStatusByID(ctx context.Context, arg UpdateSessionStatusByIDParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionStatusByID, arg.Status, arg.Error, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SimpleID,
		&i.Status,
		&i.RepoPath,
		&i.WorktreePath,
		&i.AgentModel,
		&i.AgentPrompt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionStatusBySimpleID = `-- name: UpdateSessionStatusBySimpleID :one
UPDATE sessions
SET status = ?,
    error = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE simple_id = ?
  AND status IN ('queued', 'running', 'completed')
RETURNING id, simple_id, status, repo_path, worktree_path, agent_model, agent_prompt, error, created_at, updated_at
`

type UpdateSessionStatusBySimpleIDParams struct {
	Status   SessionStatus
	Error    sql.NullString
	SimpleID string
}

func (q *Queries) UpdateSessionStatusBySimpleID(ctx context.Context, arg UpdateSessionStatusBySimpleIDParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionStatusBySimpleID, arg.Status, arg.Error, arg.SimpleID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SimpleID,
		&i.Status,
		&i.RepoPath,
		&i.WorktreePath,
		&i.AgentModel,
		&i.AgentPrompt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
