// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkpoints.sql

package db

import (
	"context"
)

const getCheckpoint = `-- name: GetCheckpoint :one
SELECT last_sequence
FROM event_log_checkpoints
WHERE topic = ?
  AND subscriber_id = ?
`

type GetCheckpointParams struct {
	Topic        string
	SubscriberID string
}

func (q *Queries) GetCheckpoint(ctx context.Context, arg GetCheckpointParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCheckpoint, arg.Topic, arg.SubscriberID)
	var last_sequence int64
	err := row.Scan(&last_sequence)
	return last_sequence, err
}

const upsertCheckpoint = `-- name: UpsertCheckpoint :exec
INSERT INTO event_log_checkpoints (
  topic,
  subscriber_id,
  last_sequence,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT(topic, subscriber_id) DO UPDATE SET
  last_sequence = excluded.last_sequence,
  updated_at = excluded.updated_at
`

type UpsertCheckpointParams struct {
	Topic        string
	SubscriberID string
	LastSequence int64
	UpdatedAt    string
}

func (q *Queries) UpsertCheckpoint(ctx context.Context, arg UpsertCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, upsertCheckpoint,
		arg.Topic,
		arg.SubscriberID,
		arg.LastSequence,
		arg.UpdatedAt,
	)
	return err
}
