// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_log.sql

package db

import (
	"context"
)

const deleteStreamEventsFromVersion = `-- name: DeleteStreamEventsFromVersion :exec
DELETE FROM event_log
WHERE topic = ?
  AND stream_id = ?
  AND stream_version >= ?
`

type DeleteStreamEventsFromVersionParams struct {
	Topic         string
	StreamID      string
	StreamVersion int64
}

func (q *Queries) DeleteStreamEventsFromVersion(ctx context.Context, arg DeleteStreamEventsFromVersionParams) error {
	_, err := q.db.ExecContext(ctx, deleteStreamEventsFromVersion, arg.Topic, arg.StreamID, arg.StreamVersion)
	return err
}

const getNextStreamVersion = `-- name: GetNextStreamVersion :one
SELECT COALESCE(MAX(stream_version), 0) + 1
FROM event_log
WHERE topic = ?
  AND stream_id = ?
`

type GetNextStreamVersionParams struct {
	Topic    string
	StreamID string
}

func (q *Queries) GetNextStreamVersion(ctx context.Context, arg GetNextStreamVersionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextStreamVersion, arg.Topic, arg.StreamID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNextTopicSequence = `-- name: GetNextTopicSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM event_log
WHERE topic = ?
`

func (q *Queries) GetNextTopicSequence(ctx context.Context, topic string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextTopicSequence, topic)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getStreamEventByID = `-- name: GetStreamEventByID :one
SELECT topic, sequence, id, stream_id, stream_version, event_type, schema_version, occurred_at, causation_id, correlation_id, payload
FROM event_log
WHERE topic = ?
  AND stream_id = ?
  AND id = ?
LIMIT 1
`

type GetStreamEventByIDParams struct {
	Topic    string
	StreamID string
	ID       string
}

func (q *Queries) GetStreamEventByID(ctx context.Context, arg GetStreamEventByIDParams) (EventLog, error) {
	row := q.db.QueryRowContext(ctx, getStreamEventByID, arg.Topic, arg.StreamID, arg.ID)
	var i EventLog
	err := row.Scan(
		&i.Topic,
		&i.Sequence,
		&i.ID,
		&i.StreamID,
		&i.StreamVersion,
		&i.EventType,
		&i.SchemaVersion,
		&i.OccurredAt,
		&i.CausationID,
		&i.CorrelationID,
		&i.Payload,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO event_log (
  topic,
  sequence,
  id,
  stream_id,
  stream_version,
  event_type,
  schema_version,
  occurred_at,
  causation_id,
  correlation_id,
  payload
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type InsertEventParams struct {
	Topic         string
	Sequence      int64
	ID            string
	StreamID      string
	StreamVersion int64
	EventType     string
	SchemaVersion int64
	OccurredAt    string
	CausationID   string
	CorrelationID string
	Payload       []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.Topic,
		arg.Sequence,
		arg.ID,
		arg.StreamID,
		arg.StreamVersion,
		arg.EventType,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.CausationID,
		arg.CorrelationID,
		arg.Payload,
	)
	return err
}

const loadStreamEvents = `-- name: LoadStreamEvents :many
SELECT topic, sequence, id, stream_id, stream_version, event_type, schema_version, occurred_at, causation_id, correlation_id, payload
FROM event_log
WHERE topic = ?
  AND stream_id = ?
  AND stream_version > ?
ORDER BY stream_version ASC
LIMIT ?
`

type LoadStreamEventsParams struct {
	Topic         string
	StreamID      string
	StreamVersion int64
	Limit         int64
}

func (q *Queries) LoadStreamEvents(ctx context.Context, arg LoadStreamEventsParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, loadStreamEvents,
		arg.Topic,
		arg.StreamID,
		arg.StreamVersion,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventLog
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.Topic,
			&i.Sequence,
			&i.ID,
			&i.StreamID,
			&i.StreamVersion,
			&i.EventType,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.CausationID,
			&i.CorrelationID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readGlobalEvents = `-- name: ReadGlobalEvents :many
SELECT topic, sequence, id, stream_id, stream_version, event_type, schema_version, occurred_at, causation_id, correlation_id, payload
FROM event_log
WHERE topic = ?
  AND sequence > ?
ORDER BY sequence ASC
LIMIT ?
`

type ReadGlobalEventsParams struct {
	Topic    string
	Sequence int64
	Limit    int64
}

func (q *Queries) ReadGlobalEvents(ctx context.Context, arg ReadGlobalEventsParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, readGlobalEvents, arg.Topic, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventLog
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.Topic,
			&i.Sequence,
			&i.ID,
			&i.StreamID,
			&i.StreamVersion,
			&i.EventType,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.CausationID,
			&i.CorrelationID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
