// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type EventLog struct {
	Topic         string
	Sequence      int64
	ID            string
	StreamID      string
	StreamVersion int64
	EventType     string
	SchemaVersion int64
	OccurredAt    string
	CausationID   string
	CorrelationID string
	Payload       []byte
}

type EventLogCheckpoint struct {
	Topic        string
	SubscriberID string
	LastSequence int64
	UpdatedAt    string
}
