// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type SessionProjection struct {
	StreamID       string
	Branch         string
	BackendID      string
	RepoPath       string
	WorktreePath   string
	RemoteUrl      string
	AgentConfig    string
	LifecycleState string
	PublicState    string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
