// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type PrLatestSnapshot struct {
	StreamID     string
	Provider     string
	RemoteUrl    string
	RepoOwner    string
	RepoName     string
	Number       int64
	HeadRef      string
	HeadSha      string
	ObservedAt   time.Time
	SnapshotJson string
}

type SessionProjection struct {
	StreamID       string
	Harness        string
	Branch         sql.NullString
	BackendID      string
	RepoPath       string
	WorktreePath   sql.NullString
	RemoteUrl      string
	AgentConfig    string
	LifecycleState string
	PublicState    string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PrNumber       sql.NullInt64
	PrState        sql.NullString
	PrCiState      sql.NullString
	PrUpdatedAt    sql.NullTime
}
