// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type SessionProjection struct {
	StreamID       string
	Harness        string
	Branch         sql.NullString
	BackendID      string
	RepoPath       string
	WorktreePath   sql.NullString
	RemoteUrl      string
	AgentConfig    string
	LifecycleState string
	PublicState    string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
