// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pr_latest_snapshot.sql

package db

import (
	"context"
	"time"
)

const getPRLatestSnapshotByRepoAndNumber = `-- name: GetPRLatestSnapshotByRepoAndNumber :one
SELECT stream_id, provider, remote_url, repo_owner, repo_name, number, head_ref, head_sha, observed_at, snapshot_json
FROM pr_latest_snapshot
WHERE provider = ?
  AND repo_owner = ?
  AND repo_name = ?
  AND number = ?
`

type GetPRLatestSnapshotByRepoAndNumberParams struct {
	Provider  string
	RepoOwner string
	RepoName  string
	Number    int64
}

func (q *Queries) GetPRLatestSnapshotByRepoAndNumber(ctx context.Context, arg GetPRLatestSnapshotByRepoAndNumberParams) (PrLatestSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getPRLatestSnapshotByRepoAndNumber,
		arg.Provider,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
	)
	var i PrLatestSnapshot
	err := row.Scan(
		&i.StreamID,
		&i.Provider,
		&i.RemoteUrl,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.HeadRef,
		&i.HeadSha,
		&i.ObservedAt,
		&i.SnapshotJson,
	)
	return i, err
}

const getPRLatestSnapshotByStreamID = `-- name: GetPRLatestSnapshotByStreamID :one
SELECT stream_id, provider, remote_url, repo_owner, repo_name, number, head_ref, head_sha, observed_at, snapshot_json
FROM pr_latest_snapshot
WHERE stream_id = ?
`

func (q *Queries) GetPRLatestSnapshotByStreamID(ctx context.Context, streamID string) (PrLatestSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getPRLatestSnapshotByStreamID, streamID)
	var i PrLatestSnapshot
	err := row.Scan(
		&i.StreamID,
		&i.Provider,
		&i.RemoteUrl,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.HeadRef,
		&i.HeadSha,
		&i.ObservedAt,
		&i.SnapshotJson,
	)
	return i, err
}

const listPRLatestSnapshotsByRemoteAndBranch = `-- name: ListPRLatestSnapshotsByRemoteAndBranch :many
SELECT stream_id, provider, remote_url, repo_owner, repo_name, number, head_ref, head_sha, observed_at, snapshot_json
FROM pr_latest_snapshot
WHERE remote_url = ?
  AND head_ref = ?
ORDER BY observed_at DESC
`

type ListPRLatestSnapshotsByRemoteAndBranchParams struct {
	RemoteUrl string
	HeadRef   string
}

func (q *Queries) ListPRLatestSnapshotsByRemoteAndBranch(ctx context.Context, arg ListPRLatestSnapshotsByRemoteAndBranchParams) ([]PrLatestSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listPRLatestSnapshotsByRemoteAndBranch, arg.RemoteUrl, arg.HeadRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrLatestSnapshot
	for rows.Next() {
		var i PrLatestSnapshot
		if err := rows.Scan(
			&i.StreamID,
			&i.Provider,
			&i.RemoteUrl,
			&i.RepoOwner,
			&i.RepoName,
			&i.Number,
			&i.HeadRef,
			&i.HeadSha,
			&i.ObservedAt,
			&i.SnapshotJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPRLatestSnapshot = `-- name: UpsertPRLatestSnapshot :exec
INSERT INTO pr_latest_snapshot (
  stream_id,
  provider,
  remote_url,
  repo_owner,
  repo_name,
  number,
  head_ref,
  head_sha,
  observed_at,
  snapshot_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(stream_id) DO UPDATE SET
  provider = excluded.provider,
  remote_url = excluded.remote_url,
  repo_owner = excluded.repo_owner,
  repo_name = excluded.repo_name,
  number = excluded.number,
  head_ref = excluded.head_ref,
  head_sha = excluded.head_sha,
  observed_at = excluded.observed_at,
  snapshot_json = excluded.snapshot_json
`

type UpsertPRLatestSnapshotParams struct {
	StreamID     string
	Provider     string
	RemoteUrl    string
	RepoOwner    string
	RepoName     string
	Number       int64
	HeadRef      string
	HeadSha      string
	ObservedAt   time.Time
	SnapshotJson string
}

func (q *Queries) UpsertPRLatestSnapshot(ctx context.Context, arg UpsertPRLatestSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertPRLatestSnapshot,
		arg.StreamID,
		arg.Provider,
		arg.RemoteUrl,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
		arg.HeadRef,
		arg.HeadSha,
		arg.ObservedAt,
		arg.SnapshotJson,
	)
	return err
}
