// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_projection.sql

package db

import (
	"context"
	"time"
)

const getSessionProjectionByBranch = `-- name: GetSessionProjectionByBranch :one
SELECT stream_id, harness, branch, backend_id, repo_path, worktree_path, remote_url, agent_config, lifecycle_state, public_state, last_error, created_at, updated_at
FROM session_projection
WHERE branch = ?
`

func (q *Queries) GetSessionProjectionByBranch(ctx context.Context, branch string) (SessionProjection, error) {
	row := q.db.QueryRowContext(ctx, getSessionProjectionByBranch, branch)
	var i SessionProjection
	err := row.Scan(
		&i.StreamID,
		&i.Harness,
		&i.Branch,
		&i.BackendID,
		&i.RepoPath,
		&i.WorktreePath,
		&i.RemoteUrl,
		&i.AgentConfig,
		&i.LifecycleState,
		&i.PublicState,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionProjectionByStreamID = `-- name: GetSessionProjectionByStreamID :one
SELECT stream_id, harness, branch, backend_id, repo_path, worktree_path, remote_url, agent_config, lifecycle_state, public_state, last_error, created_at, updated_at
FROM session_projection
WHERE stream_id = ?
`

func (q *Queries) GetSessionProjectionByStreamID(ctx context.Context, streamID string) (SessionProjection, error) {
	row := q.db.QueryRowContext(ctx, getSessionProjectionByStreamID, streamID)
	var i SessionProjection
	err := row.Scan(
		&i.StreamID,
		&i.Harness,
		&i.Branch,
		&i.BackendID,
		&i.RepoPath,
		&i.WorktreePath,
		&i.RemoteUrl,
		&i.AgentConfig,
		&i.LifecycleState,
		&i.PublicState,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSessionProjectionRefs = `-- name: ListActiveSessionProjectionRefs :many
SELECT stream_id, harness, branch, backend_id, repo_path, worktree_path, remote_url, agent_config, lifecycle_state, public_state, last_error, created_at, updated_at
FROM session_projection
WHERE public_state IN ('queued', 'running')
ORDER BY updated_at DESC
`

func (q *Queries) ListActiveSessionProjectionRefs(ctx context.Context) ([]SessionProjection, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSessionProjectionRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionProjection
	for rows.Next() {
		var i SessionProjection
		if err := rows.Scan(
			&i.StreamID,
			&i.Harness,
			&i.Branch,
			&i.BackendID,
			&i.RepoPath,
			&i.WorktreePath,
			&i.RemoteUrl,
			&i.AgentConfig,
			&i.LifecycleState,
			&i.PublicState,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSessionProjectionItems = `-- name: ListAllSessionProjectionItems :many
SELECT stream_id, repo_path, remote_url, branch, public_state
FROM session_projection
ORDER BY updated_at DESC
LIMIT 100
`

type ListAllSessionProjectionItemsRow struct {
	StreamID    string
	RepoPath    string
	RemoteUrl   string
	Branch      string
	PublicState string
}

func (q *Queries) ListAllSessionProjectionItems(ctx context.Context) ([]ListAllSessionProjectionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessionProjectionItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSessionProjectionItemsRow
	for rows.Next() {
		var i ListAllSessionProjectionItemsRow
		if err := rows.Scan(
			&i.StreamID,
			&i.RepoPath,
			&i.RemoteUrl,
			&i.Branch,
			&i.PublicState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionProjectionItemsByStatuses = `-- name: ListSessionProjectionItemsByStatuses :many
SELECT stream_id, repo_path, remote_url, branch, public_state
FROM session_projection
WHERE (? = '') OR (',' || ? || ',') LIKE '%,' || public_state || ',%'
  AND (? = '' OR stream_id < ?)
ORDER BY stream_id DESC
LIMIT ?;
`

func (q *Queries) ListSessionProjectionItemsByStatuses(ctx context.Context, statuses string, statuses2 string, cursor string, cursor2 string, limit int) ([]ListAllSessionProjectionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionProjectionItemsByStatuses, statuses, statuses2, cursor, cursor2, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSessionProjectionItemsRow
	for rows.Next() {
		var i ListAllSessionProjectionItemsRow
		if err := rows.Scan(
			&i.StreamID,
			&i.RepoPath,
			&i.RemoteUrl,
			&i.Branch,
			&i.PublicState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHydratableSessionProjectionRefs = `-- name: ListHydratableSessionProjectionRefs :many
SELECT stream_id, harness, branch, backend_id, repo_path, worktree_path, remote_url, agent_config, lifecycle_state, public_state, last_error, created_at, updated_at
FROM session_projection
WHERE public_state IN ('queued', 'running', 'completing', 'deleting')
ORDER BY updated_at DESC
`

func (q *Queries) ListHydratableSessionProjectionRefs(ctx context.Context) ([]SessionProjection, error) {
	rows, err := q.db.QueryContext(ctx, listHydratableSessionProjectionRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionProjection
	for rows.Next() {
		var i SessionProjection
		if err := rows.Scan(
			&i.StreamID,
			&i.Harness,
			&i.Branch,
			&i.BackendID,
			&i.RepoPath,
			&i.WorktreePath,
			&i.RemoteUrl,
			&i.AgentConfig,
			&i.LifecycleState,
			&i.PublicState,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReusableSessionProjectionRefs = `-- name: ListReusableSessionProjectionRefs :many
SELECT stream_id, harness, branch, backend_id, repo_path, worktree_path, remote_url, agent_config, lifecycle_state, public_state, last_error, created_at, updated_at
FROM session_projection
WHERE public_state = 'completed'
  AND repo_path = ?
  AND backend_id = ?
ORDER BY updated_at DESC
`

type ListReusableSessionProjectionRefsParams struct {
	RepoPath  string
	BackendID string
}

func (q *Queries) ListReusableSessionProjectionRefs(ctx context.Context, arg ListReusableSessionProjectionRefsParams) ([]SessionProjection, error) {
	rows, err := q.db.QueryContext(ctx, listReusableSessionProjectionRefs, arg.RepoPath, arg.BackendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionProjection
	for rows.Next() {
		var i SessionProjection
		if err := rows.Scan(
			&i.StreamID,
			&i.Harness,
			&i.Branch,
			&i.BackendID,
			&i.RepoPath,
			&i.WorktreePath,
			&i.RemoteUrl,
			&i.AgentConfig,
			&i.LifecycleState,
			&i.PublicState,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleSessionProjectionItems = `-- name: ListVisibleSessionProjectionItems :many
SELECT stream_id, repo_path, remote_url, branch, public_state
FROM session_projection
WHERE public_state IN ('queued', 'running', 'completing')
ORDER BY updated_at DESC
LIMIT 100
`

type ListVisibleSessionProjectionItemsRow struct {
	StreamID    string
	RepoPath    string
	RemoteUrl   string
	Branch      string
	PublicState string
}

func (q *Queries) ListVisibleSessionProjectionItems(ctx context.Context) ([]ListVisibleSessionProjectionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleSessionProjectionItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisibleSessionProjectionItemsRow
	for rows.Next() {
		var i ListVisibleSessionProjectionItemsRow
		if err := rows.Scan(
			&i.StreamID,
			&i.RepoPath,
			&i.RemoteUrl,
			&i.Branch,
			&i.PublicState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchSessionProjection = `-- name: PatchSessionProjection :exec
UPDATE session_projection
SET lifecycle_state = ?,
    public_state = ?,
    last_error = ?,
    updated_at = ?
WHERE stream_id = ?
`

type PatchSessionProjectionParams struct {
	LifecycleState string
	PublicState    string
	LastError      string
	UpdatedAt      time.Time
	StreamID       string
}

func (q *Queries) PatchSessionProjection(ctx context.Context, arg PatchSessionProjectionParams) error {
	_, err := q.db.ExecContext(ctx, patchSessionProjection,
		arg.LifecycleState,
		arg.PublicState,
		arg.LastError,
		arg.UpdatedAt,
		arg.StreamID,
	)
	return err
}

const upsertSessionProjection = `-- name: UpsertSessionProjection :exec
INSERT INTO session_projection (
  stream_id,
  harness,
  branch,
  backend_id,
  repo_path,
  worktree_path,
  remote_url,
  agent_config,
  lifecycle_state,
  public_state,
  last_error,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT(stream_id) DO UPDATE SET
  harness = excluded.harness,
  branch = excluded.branch,
  backend_id = excluded.backend_id,
  repo_path = excluded.repo_path,
  worktree_path = excluded.worktree_path,
  remote_url = excluded.remote_url,
  agent_config = excluded.agent_config,
  lifecycle_state = excluded.lifecycle_state,
  public_state = excluded.public_state,
  last_error = excluded.last_error,
  updated_at = excluded.updated_at
`

type UpsertSessionProjectionParams struct {
	StreamID       string
	Harness        string
	Branch         string
	BackendID      string
	RepoPath       string
	WorktreePath   string
	RemoteUrl      string
	AgentConfig    string
	LifecycleState string
	PublicState    string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpsertSessionProjection(ctx context.Context, arg UpsertSessionProjectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionProjection,
		arg.StreamID,
		arg.Harness,
		arg.Branch,
		arg.BackendID,
		arg.RepoPath,
		arg.WorktreePath,
		arg.RemoteUrl,
		arg.AgentConfig,
		arg.LifecycleState,
		arg.PublicState,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
